/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutPebRouteImport } from './routes/about-peb'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AboutPebAccessoriesRouteImport } from './routes/about-peb_.accessories'
import { Route as AboutPebCladdingSystemRouteImport } from './routes/about-peb_.cladding-system'
import { Route as AboutPebMezzanineFloorsRouteImport } from './routes/about-peb_.mezzanine-floors'
import { Route as AboutPebPrimarySystemRouteImport } from './routes/about-peb_.primary-system'
import { Route as AboutPebSecondarySystemRouteImport } from './routes/about-peb_.secondary-system'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as ApiPublicEnquiryRouteImport } from './routes/api/public/enquiry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPebRoute = AboutPebRouteImport.update({
  id: '/about-peb',
  path: '/about-peb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AboutPebAccessoriesRoute = AboutPebAccessoriesRouteImport.update({
  id: '/about-peb_/accessories',
  path: '/about-peb/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPebCladdingSystemRoute = AboutPebCladdingSystemRouteImport.update({
  id: '/about-peb_/cladding-system',
  path: '/about-peb/cladding-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPebMezzanineFloorsRoute = AboutPebMezzanineFloorsRouteImport.update({
  id: '/about-peb_/mezzanine-floors',
  path: '/about-peb/mezzanine-floors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPebPrimarySystemRoute = AboutPebPrimarySystemRouteImport.update({
  id: '/about-peb_/primary-system',
  path: '/about-peb/primary-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPebSecondarySystemRoute = AboutPebSecondarySystemRouteImport.update({
  id: '/about-peb_/secondary-system',
  path: '/about-peb/secondary-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicEnquiryRoute = ApiPublicEnquiryRouteImport.update({
  id: '/api/public/enquiry',
  path: '/api/public/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-peb': typeof AboutPebRoute
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/about-peb/accessories': typeof AboutPebAccessoriesRoute
  '/about-peb/cladding-system': typeof AboutPebCladdingSystemRoute
  '/about-peb/mezzanine-floors': typeof AboutPebMezzanineFloorsRoute
  '/about-peb/primary-system': typeof AboutPebPrimarySystemRoute
  '/about-peb/secondary-system': typeof AboutPebSecondarySystemRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/enquiry': typeof ApiPublicEnquiryRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-peb': typeof AboutPebRoute
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about-peb/accessories': typeof AboutPebAccessoriesRoute
  '/about-peb/cladding-system': typeof AboutPebCladdingSystemRoute
  '/about-peb/mezzanine-floors': typeof AboutPebMezzanineFloorsRoute
  '/about-peb/primary-system': typeof AboutPebPrimarySystemRoute
  '/about-peb/secondary-system': typeof AboutPebSecondarySystemRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/enquiry': typeof ApiPublicEnquiryRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/about-peb': typeof AboutPebRoute
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/about-peb_/accessories': typeof AboutPebAccessoriesRoute
  '/about-peb_/cladding-system': typeof AboutPebCladdingSystemRoute
  '/about-peb_/mezzanine-floors': typeof AboutPebMezzanineFloorsRoute
  '/about-peb_/primary-system': typeof AboutPebPrimarySystemRoute
  '/about-peb_/secondary-system': typeof AboutPebSecondarySystemRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/enquiry': typeof ApiPublicEnquiryRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-peb'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/about-peb/accessories'
    | '/about-peb/cladding-system'
    | '/about-peb/mezzanine-floors'
    | '/about-peb/primary-system'
    | '/about-peb/secondary-system'
    | '/projects/$slug'
    | '/projects/'
    | '/admin/enquiries'
    | '/admin/projects'
    | '/admin/users'
    | '/api/public/enquiry'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-peb'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about-peb/accessories'
    | '/about-peb/cladding-system'
    | '/about-peb/mezzanine-floors'
    | '/about-peb/primary-system'
    | '/about-peb/secondary-system'
    | '/projects/$slug'
    | '/projects'
    | '/admin/enquiries'
    | '/admin/projects'
    | '/admin/users'
    | '/api/public/enquiry'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/about-peb'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/about-peb_/accessories'
    | '/about-peb_/cladding-system'
    | '/about-peb_/mezzanine-floors'
    | '/about-peb_/primary-system'
    | '/about-peb_/secondary-system'
    | '/projects/$slug'
    | '/projects/'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/users'
    | '/api/public/enquiry'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AboutPebRoute: typeof AboutPebRoute
  AuthRoute: typeof AuthRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AboutPebAccessoriesRoute: typeof AboutPebAccessoriesRoute
  AboutPebCladdingSystemRoute: typeof AboutPebCladdingSystemRoute
  AboutPebMezzanineFloorsRoute: typeof AboutPebMezzanineFloorsRoute
  AboutPebPrimarySystemRoute: typeof AboutPebPrimarySystemRoute
  AboutPebSecondarySystemRoute: typeof AboutPebSecondarySystemRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicEnquiryRoute: typeof ApiPublicEnquiryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-peb': {
      id: '/about-peb'
      path: '/about-peb'
      fullPath: '/about-peb'
      preLoaderRoute: typeof AboutPebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/about-peb_/accessories': {
      id: '/about-peb_/accessories'
      path: '/about-peb/accessories'
      fullPath: '/about-peb/accessories'
      preLoaderRoute: typeof AboutPebAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-peb_/cladding-system': {
      id: '/about-peb_/cladding-system'
      path: '/about-peb/cladding-system'
      fullPath: '/about-peb/cladding-system'
      preLoaderRoute: typeof AboutPebCladdingSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-peb_/mezzanine-floors': {
      id: '/about-peb_/mezzanine-floors'
      path: '/about-peb/mezzanine-floors'
      fullPath: '/about-peb/mezzanine-floors'
      preLoaderRoute: typeof AboutPebMezzanineFloorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-peb_/primary-system': {
      id: '/about-peb_/primary-system'
      path: '/about-peb/primary-system'
      fullPath: '/about-peb/primary-system'
      preLoaderRoute: typeof AboutPebPrimarySystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-peb_/secondary-system': {
      id: '/about-peb_/secondary-system'
      path: '/about-peb/secondary-system'
      fullPath: '/about-peb/secondary-system'
      preLoaderRoute: typeof AboutPebSecondarySystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/enquiry': {
      id: '/api/public/enquiry'
      path: '/api/public/enquiry'
      fullPath: '/api/public/enquiry'
      preLoaderRoute: typeof ApiPublicEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AboutPebRoute: AboutPebRoute,
  AuthRoute: AuthRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AboutPebAccessoriesRoute: AboutPebAccessoriesRoute,
  AboutPebCladdingSystemRoute: AboutPebCladdingSystemRoute,
  AboutPebMezzanineFloorsRoute: AboutPebMezzanineFloorsRoute,
  AboutPebPrimarySystemRoute: AboutPebPrimarySystemRoute,
  AboutPebSecondarySystemRoute: AboutPebSecondarySystemRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicEnquiryRoute: ApiPublicEnquiryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
