-- ============================================================================
-- Replace the placeholder project records with the fourteen real projects
-- documented in the Darshan Steel Group product catalogue (Edition 3).
--
-- The previous seed inserted six invented placeholder records
-- ('[PROJECT 01 NAME]' and so on) with verified = false. Those are removed
-- here and replaced with the real client records: name, building type,
-- location and built-up area are reproduced from the catalogue.
--
-- Kept deliberately empty:
--   year — the catalogue dates none of these projects. The site omits the
--          Year row when this is empty rather than printing a guess.
--
-- This file mirrors src/data/projects.ts exactly; that module is the
-- fallback used when the database is unreachable. Regenerate both together.
-- ============================================================================

BEGIN;

-- Remove only the placeholder rows created by the original seed.
DELETE FROM public.projects WHERE slug IN (
  'project-01','project-02','project-03','project-04','project-05','project-06'
);

INSERT INTO public.projects (
  idx, slug, name, building_type, location, year, area, scope, verified,
  photo, plate, overview, challenge, approach, execution, result,
  technical, gallery, sort_order
) VALUES
('01', 'lemit-paper-llp', 'Lemit Paper LLP', 'Paper Mill', 'Morbi, Gujarat', '', '19,920 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-01.jpg', 'plant', 'A paper mill is a continuous-process building. Machine lines run the length of the hall, stock and reels move by overhead crane, and the structure has to stay clear of both. The frame is sized around the machine envelope rather than the other way round.', 'Paper machines are long, heavy and intolerant of movement. Crane duty is constant, humidity is high, and any column landing inside the machine line would force the process to work around the building.', 'Clear-span portal frames keep the machine hall column-free. Crane brackets and gantry beams are designed into the columns as part of the same analysis, so the crane load path is resolved before fabrication rather than bolted on afterwards.', 'Members are cut, drilled and welded on CNC lines, blast-cleaned to SA 2.5 and primed before dispatch. Steel leaves the shop bundled in erection sequence so the frame goes up in the order the drawings assume.', 'A column-free process hall with the crane system integrated into the building structure, supplied and erected under single-point responsibility.', '[{"label":"Sector","value":"Paper Mill"},{"label":"Built-up area","value":"19,920 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-erection.jpg","alt":"Paper Mill — rigger working at height during steel erection","plate":"erection","label":"PLATE 01"},{"src":"/images/gallery-weld-detail.jpg","alt":"Paper Mill — welding a steel joint, arc light on the metal","plate":"blueprint","label":"PLATE 02"},{"src":"/images/gallery-shop-floor.jpg","alt":"Paper Mill — operator working a machine on the fabrication floor","plate":"plant","label":"PLATE 03"},{"src":"/images/gallery-site-progress.jpg","alt":"Paper Mill — plant working beside a partly clad steel building","plate":"warehouse","label":"PLATE 04"}]'::jsonb, 1),
('02', 'ambani-paper-llp', 'Ambani Paper LLP', 'Paper Mill', 'Morbi, Gujarat', '', '10,490 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-02.jpg', 'plant', 'A paper mill is a continuous-process building. Machine lines run the length of the hall, stock and reels move by overhead crane, and the structure has to stay clear of both. The frame is sized around the machine envelope rather than the other way round.', 'Paper machines are long, heavy and intolerant of movement. Crane duty is constant, humidity is high, and any column landing inside the machine line would force the process to work around the building.', 'Clear-span portal frames keep the machine hall column-free. Crane brackets and gantry beams are designed into the columns as part of the same analysis, so the crane load path is resolved before fabrication rather than bolted on afterwards.', 'Members are cut, drilled and welded on CNC lines, blast-cleaned to SA 2.5 and primed before dispatch. Steel leaves the shop bundled in erection sequence so the frame goes up in the order the drawings assume.', 'A column-free process hall with the crane system integrated into the building structure, supplied and erected under single-point responsibility.', '[{"label":"Sector","value":"Paper Mill"},{"label":"Built-up area","value":"10,490 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-site-progress.jpg","alt":"Paper Mill — plant working beside a partly clad steel building","plate":"warehouse","label":"PLATE 01"},{"src":"/images/gallery-frame-sky.jpg","alt":"Paper Mill — steel portal frame standing against an overcast sky","plate":"frames","label":"PLATE 02"},{"src":"/images/gallery-racking.jpg","alt":"Paper Mill — labelled cartons on warehouse racking","plate":"aerial","label":"PLATE 03"},{"src":"/images/gallery-structure-detail.jpg","alt":"Paper Mill — detail of a grey steel structure in daylight","plate":"frames","label":"PLATE 04"}]'::jsonb, 2),
('03', 'mascot-forge-pvt-ltd', 'Mascot Forge Pvt. Ltd.', 'Forging Plant', 'Rajkot, Gujarat', '', '12,020 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-03.jpg', 'plant', 'A forging plant puts more into its building than most. Hammers and presses transmit shock into the floor and frame, material moves overhead continuously, and radiant heat drives the ventilation strategy.', 'Impact loading and heavy crane duty govern the frame, while heat and scale demand a roof that can ventilate and a coating system that survives the environment.', 'Frames are checked for crane, wind and seismic combinations together rather than in isolation. Ridge ventilation and roof monitors are set into the roof geometry, and the coating specification is chosen for the operating environment.', 'Built-up sections are fabricated from plate so depth follows the bending moment, then inspected at fixed hold points for weld quality and coating thickness before release.', 'A crane-served forging bay engineered for impact duty and ventilated through the roof structure itself.', '[{"label":"Sector","value":"Forging Plant"},{"label":"Built-up area","value":"12,020 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-structure-detail.jpg","alt":"Forging Plant — detail of a grey steel structure in daylight","plate":"frames","label":"PLATE 01"},{"src":"/images/gallery-crane-lift.jpg","alt":"Forging Plant — crane lifting a load on an industrial site","plate":"erection","label":"PLATE 02"},{"src":"/images/gallery-erection.jpg","alt":"Forging Plant — rigger working at height during steel erection","plate":"erection","label":"PLATE 03"},{"src":"/images/gallery-weld-detail.jpg","alt":"Forging Plant — welding a steel joint, arc light on the metal","plate":"blueprint","label":"PLATE 04"}]'::jsonb, 3),
('04', 'davat-beverages-pvt-ltd', 'Davat Beverages Pvt. Ltd.', 'Beverage Plant', 'Gondal, Gujarat', '', '10,140 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-04.jpg', 'warehouse', 'Beverage production combines wet processing, filling lines and finished-goods storage under one roof, each with a different demand on the envelope.', 'Wash-down areas need corrosion-conscious steelwork, filling halls need clear floor for line changes, and the warehouse end needs height for pallet storage — inside a single continuous structure.', 'The frame is zoned: clear spans over the process floor, higher eaves over storage, and the coating specification stepped to match the wet and dry zones.', 'Fabrication is sequenced by erection bay so the structure closes in the order the fit-out needs it. Sheeting and flashing are supplied with the frame as one package.', 'A single structure carrying process, filling and storage, each zone detailed for the conditions it actually operates in.', '[{"label":"Sector","value":"Beverage Plant"},{"label":"Built-up area","value":"10,140 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-weld-detail.jpg","alt":"Beverage Plant — welding a steel joint, arc light on the metal","plate":"blueprint","label":"PLATE 01"},{"src":"/images/gallery-shop-floor.jpg","alt":"Beverage Plant — operator working a machine on the fabrication floor","plate":"plant","label":"PLATE 02"},{"src":"/images/gallery-site-progress.jpg","alt":"Beverage Plant — plant working beside a partly clad steel building","plate":"warehouse","label":"PLATE 03"},{"src":"/images/gallery-frame-sky.jpg","alt":"Beverage Plant — steel portal frame standing against an overcast sky","plate":"frames","label":"PLATE 04"}]'::jsonb, 4),
('05', 'fortune-enterprise', 'Fortune Enterprise', 'Logistics Facility', 'Rajkot, Gujarat', '', '11,850 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-05.jpg', 'warehouse', 'A logistics building is a machine for moving pallets. Rack lines, aisle widths, turning circles and dock positions are fixed before the structure is, and the grid has to agree with all of them.', 'A column in an operating aisle costs storage positions for the life of the building. Eave height is set by vertical storage, and high, light structures are governed by wind uplift rather than gravity load.', 'Bay spacing is taken from the racking layout before the frame is sized. High-eave framing is checked for uplift and for the deflection limits the cladding system needs, and dock canopies are detailed with the main frame.', 'Members are fabricated and bundled by erection bay. Dock structures and canopies are dispatched alongside the frame so the envelope closes in one pass.', 'A distribution facility whose grid matches its racking layout, with docks and canopies delivered as part of the same structural package.', '[{"label":"Sector","value":"Logistics Facility"},{"label":"Built-up area","value":"11,850 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-frame-sky.jpg","alt":"Logistics Facility — steel portal frame standing against an overcast sky","plate":"frames","label":"PLATE 01"},{"src":"/images/gallery-racking.jpg","alt":"Logistics Facility — labelled cartons on warehouse racking","plate":"aerial","label":"PLATE 02"},{"src":"/images/gallery-structure-detail.jpg","alt":"Logistics Facility — detail of a grey steel structure in daylight","plate":"frames","label":"PLATE 03"},{"src":"/images/gallery-crane-lift.jpg","alt":"Logistics Facility — crane lifting a load on an industrial site","plate":"erection","label":"PLATE 04"}]'::jsonb, 5),
('06', 'shilpan-boardlam-pvt-ltd', 'Shilpan Boardlam Pvt. Ltd.', 'Plywood & Laminates Plant', 'Rajkot, Gujarat', '', '12,990 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-06.jpg', 'plant', 'Plywood and laminate production runs presses, dryers and long panel lines under a single large-span roof, with dust and heat extraction routed through the structure.', 'Panel lines demand uninterrupted floor length, presses concentrate load, and extraction ductwork needs support points that were planned rather than improvised.', 'Long clear spans keep the panel line uninterrupted. Duct and equipment support points are carried by the frame and designed in at detailing stage rather than added on site.', 'A single coordinated model drives shop drawings, erection drawings and material lists, so what is fabricated matches what is erected.', 'A large-span production hall with service and equipment supports designed into the frame.', '[{"label":"Sector","value":"Plywood & Laminates Plant"},{"label":"Built-up area","value":"12,990 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-crane-lift.jpg","alt":"Plywood & Laminates Plant — crane lifting a load on an industrial site","plate":"erection","label":"PLATE 01"},{"src":"/images/gallery-erection.jpg","alt":"Plywood & Laminates Plant — rigger working at height during steel erection","plate":"erection","label":"PLATE 02"},{"src":"/images/gallery-weld-detail.jpg","alt":"Plywood & Laminates Plant — welding a steel joint, arc light on the metal","plate":"blueprint","label":"PLATE 03"},{"src":"/images/gallery-shop-floor.jpg","alt":"Plywood & Laminates Plant — operator working a machine on the fabrication floor","plate":"plant","label":"PLATE 04"}]'::jsonb, 6),
('07', 'actionware-india-pvt-ltd', 'Actionware India Pvt. Ltd.', 'Home Appliance Plant', 'Morbi, Gujarat', '', '2,550 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-01.jpg', 'frames', 'Appliance manufacturing mixes press work, assembly and finished-goods storage, with material moving between them throughout the shift.', 'Assembly layouts change more often than buildings do, so usable clear area and the ability to reconfigure matter more than any single fixed arrangement.', 'Clear-span framing maximises usable floor within the permitted footprint, with end bays detailed so the building can be extended by adding bays rather than by structural rework.', 'Components are produced in-house on CNC cutting, welding and forming lines, then dispatched with packing lists that match the erection drawings mark for mark.', 'A flexible production and storage envelope with provision for future extension built into the end bays.', '[{"label":"Sector","value":"Home Appliance Plant"},{"label":"Built-up area","value":"2,550 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-shop-floor.jpg","alt":"Home Appliance Plant — operator working a machine on the fabrication floor","plate":"plant","label":"PLATE 01"},{"src":"/images/gallery-site-progress.jpg","alt":"Home Appliance Plant — plant working beside a partly clad steel building","plate":"warehouse","label":"PLATE 02"},{"src":"/images/gallery-frame-sky.jpg","alt":"Home Appliance Plant — steel portal frame standing against an overcast sky","plate":"frames","label":"PLATE 03"},{"src":"/images/gallery-racking.jpg","alt":"Home Appliance Plant — labelled cartons on warehouse racking","plate":"aerial","label":"PLATE 04"}]'::jsonb, 7),
('08', 'action-metal-and-tubes-llp', 'Action Metal & Tubes LLP', 'Metal & Tube Plant', 'Rajkot, Gujarat', '', '4,700 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-02.jpg', 'plant', 'Metal and tube production is a material-handling problem first. Long stock arrives, moves through the line and leaves, and the crane runs almost continuously.', 'Long material runs need bay length and unobstructed crane travel; heavy stock loads the floor and the gantry alike.', 'Bay spacing and crane span are optimised together for cost efficiency, with crane rail beams designed as part of the building system rather than as a separate structure.', 'Crane beams are supplied with all fixing components, cleats and fasteners, together with static calculations and erection drawings.', 'A crane-served production bay with the rail beams integrated into the building frame from the first analysis run.', '[{"label":"Sector","value":"Metal & Tube Plant"},{"label":"Built-up area","value":"4,700 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-racking.jpg","alt":"Metal & Tube Plant — labelled cartons on warehouse racking","plate":"aerial","label":"PLATE 01"},{"src":"/images/gallery-structure-detail.jpg","alt":"Metal & Tube Plant — detail of a grey steel structure in daylight","plate":"frames","label":"PLATE 02"},{"src":"/images/gallery-crane-lift.jpg","alt":"Metal & Tube Plant — crane lifting a load on an industrial site","plate":"erection","label":"PLATE 03"},{"src":"/images/gallery-erection.jpg","alt":"Metal & Tube Plant — rigger working at height during steel erection","plate":"erection","label":"PLATE 04"}]'::jsonb, 8),
('09', 'pelican-rotoflex-pvt-ltd', 'Pelican Rotoflex Pvt. Ltd.', 'Machinery Manufacturing Plant', 'Jamnagar, Gujarat', '', '4,650 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-03.jpg', 'plant', 'A machine-tool plant needs stable, well-lit floor area and dependable overhead handling to move workpieces between stations.', 'Machining tolerances make the plant sensitive to vibration and to poor light, while assembly needs clear height for lifting.', 'Clear-span frames give unobstructed floor for machine layout, with daylight panels and ridge ventilation set into the roof to cut reliance on artificial light.', 'Members are shot-blasted to SA 2.5 and primed to 80–120 microns for protection through transport and erection, then assembled with high-tensile bolted connections.', 'A column-free machining and assembly hall lit through the roof and served by overhead cranes.', '[{"label":"Sector","value":"Machinery Manufacturing Plant"},{"label":"Built-up area","value":"4,650 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-erection.jpg","alt":"Machinery Manufacturing Plant — rigger working at height during steel erection","plate":"erection","label":"PLATE 01"},{"src":"/images/gallery-weld-detail.jpg","alt":"Machinery Manufacturing Plant — welding a steel joint, arc light on the metal","plate":"blueprint","label":"PLATE 02"},{"src":"/images/gallery-shop-floor.jpg","alt":"Machinery Manufacturing Plant — operator working a machine on the fabrication floor","plate":"plant","label":"PLATE 03"},{"src":"/images/gallery-site-progress.jpg","alt":"Machinery Manufacturing Plant — plant working beside a partly clad steel building","plate":"warehouse","label":"PLATE 04"}]'::jsonb, 9),
('10', 'sicer-italian-ceramic-surfaces', 'Sicer Italian Ceramic Surfaces', 'Chemical Plant', 'Morbi, Gujarat', '', '4,150 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-04.jpg', 'frames', 'Chemical and ceramic-surface production places a corrosive, often humid load on everything the structure is made of.', 'Standard industrial coatings do not survive a chemical environment, and every fixing, flashing and support point is a place for corrosion to start.', 'The coating specification is set for the operating environment rather than to a general industrial default, with optional corrosion-protection paint over the standard primer.', 'Dry film thickness is measured and recorded across each coated member before it leaves the shop, and non-conformances are closed prior to dispatch.', 'A production building specified and coated for the environment it has to stand in.', '[{"label":"Sector","value":"Chemical Plant"},{"label":"Built-up area","value":"4,150 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-site-progress.jpg","alt":"Chemical Plant — plant working beside a partly clad steel building","plate":"warehouse","label":"PLATE 01"},{"src":"/images/gallery-frame-sky.jpg","alt":"Chemical Plant — steel portal frame standing against an overcast sky","plate":"frames","label":"PLATE 02"},{"src":"/images/gallery-racking.jpg","alt":"Chemical Plant — labelled cartons on warehouse racking","plate":"aerial","label":"PLATE 03"},{"src":"/images/gallery-structure-detail.jpg","alt":"Chemical Plant — detail of a grey steel structure in daylight","plate":"frames","label":"PLATE 04"}]'::jsonb, 10),
('11', 'tileque-surfaces-llp', 'Tileque Surfaces LLP', 'Decorative Surfaces Plant', 'Morbi, Gujarat', '', '11,850 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-05.jpg', 'frames', 'A decorative-surfaces plant is part factory and part showroom: production behind, a client-facing frontage in front, both carried by the same structure.', 'Steel that is visible in the finished building has to meet a finish standard as well as a strength standard, and the frontage has to carry glazing without compromising the production span behind it.', 'Facade and glazing support systems are coordinated with the architect while the production hall behind is framed for clear span. Exposed connections are detailed to be seen.', 'Exposed members are handled and packed to protect the coating in transit, and erected with the same care the finish standard implies.', 'A production facility with an architectural frontage, both delivered by one structural package.', '[{"label":"Sector","value":"Decorative Surfaces Plant"},{"label":"Built-up area","value":"11,850 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-structure-detail.jpg","alt":"Decorative Surfaces Plant — detail of a grey steel structure in daylight","plate":"frames","label":"PLATE 01"},{"src":"/images/gallery-crane-lift.jpg","alt":"Decorative Surfaces Plant — crane lifting a load on an industrial site","plate":"erection","label":"PLATE 02"},{"src":"/images/gallery-erection.jpg","alt":"Decorative Surfaces Plant — rigger working at height during steel erection","plate":"erection","label":"PLATE 03"},{"src":"/images/gallery-weld-detail.jpg","alt":"Decorative Surfaces Plant — welding a steel joint, arc light on the metal","plate":"blueprint","label":"PLATE 04"}]'::jsonb, 11),
('12', 'honey-bunny', 'Honey Bunny', 'Hygiene Products Plant', 'Morbi, Gujarat', '', '12,990 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-06.jpg', 'warehouse', 'Hygiene-product manufacture runs high-speed converting lines under clean, dust-controlled conditions, with bulky finished goods stored on site.', 'Converting lines need continuous clear floor, air handling needs support from the roof structure, and the storage end needs height that the production end does not.', 'Long clear spans carry the converting hall, with roof-mounted plant supported on designed points and eave height stepped to suit storage.', 'Insulation, liner panels and sealants are supplied with the frame so the envelope is closed as a single specified system rather than assembled from parts.', 'A clean, well-sealed production and storage envelope built as one integrated package.', '[{"label":"Sector","value":"Hygiene Products Plant"},{"label":"Built-up area","value":"12,990 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-weld-detail.jpg","alt":"Hygiene Products Plant — welding a steel joint, arc light on the metal","plate":"blueprint","label":"PLATE 01"},{"src":"/images/gallery-shop-floor.jpg","alt":"Hygiene Products Plant — operator working a machine on the fabrication floor","plate":"plant","label":"PLATE 02"},{"src":"/images/gallery-site-progress.jpg","alt":"Hygiene Products Plant — plant working beside a partly clad steel building","plate":"warehouse","label":"PLATE 03"},{"src":"/images/gallery-frame-sky.jpg","alt":"Hygiene Products Plant — steel portal frame standing against an overcast sky","plate":"frames","label":"PLATE 04"}]'::jsonb, 12),
('13', 'slogan-polyfilm-pvt-ltd', 'Slogan Polyfilm Pvt. Ltd.', 'BOPP Film Plant', 'Morbi, Gujarat', '', '8,940 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-01.jpg', 'plant', 'A BOPP film line is one of the longest continuous machines in plastics processing, and the building is effectively wrapped around it.', 'The line dictates the building length, the orientation and the crane run. Nothing structural can interrupt it, and the roof has to carry extraction and services along its full length.', 'Multi-span framing carries the length the line needs while keeping the machine envelope clear, with service and duct supports designed into the rafters.', 'Fabrication is programmed against the erection sequence so the frame advances along the line in one direction without rework.', 'A long-span process building planned around the machine it exists to house.', '[{"label":"Sector","value":"BOPP Film Plant"},{"label":"Built-up area","value":"8,940 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-frame-sky.jpg","alt":"BOPP Film Plant — steel portal frame standing against an overcast sky","plate":"frames","label":"PLATE 01"},{"src":"/images/gallery-racking.jpg","alt":"BOPP Film Plant — labelled cartons on warehouse racking","plate":"aerial","label":"PLATE 02"},{"src":"/images/gallery-structure-detail.jpg","alt":"BOPP Film Plant — detail of a grey steel structure in daylight","plate":"frames","label":"PLATE 03"},{"src":"/images/gallery-crane-lift.jpg","alt":"BOPP Film Plant — crane lifting a load on an industrial site","plate":"erection","label":"PLATE 04"}]'::jsonb, 13),
('14', 'g-m-engineering-pvt-ltd', 'G.M. Engineering Pvt. Ltd.', 'Industrial Valve Plant', 'Rajkot, Gujarat', '', '7,300 Sq. Mt.', ARRAY['Design & Engineering','Fabrication','Supply','Erection'], true, '/images/project-02.jpg', 'plant', 'Valve manufacture combines machining, assembly, testing and despatch, each needing different handling and floor conditions.', 'Heavy castings move constantly between stations, so crane coverage and floor loading matter across the whole footprint, not just in one bay.', 'Crane provision is designed across the bays that need it, with columns detailed for brackets from the outset and bay spacing optimised against crane span.', 'All fixing components, cleats and fasteners are supplied with the structure, and rail alignment is surveyed during erection before the crane is commissioned.', 'A multi-station manufacturing building with crane coverage designed across the working footprint.', '[{"label":"Sector","value":"Industrial Valve Plant"},{"label":"Built-up area","value":"7,300 Sq. Mt."},{"label":"Scope","value":"Design, fabrication, supply & erection"},{"label":"Structural steel","value":"345 MPa primary & secondary members"},{"label":"Roof & wall sheeting","value":"S550 high-tensile, 0.50–0.80 mm"},{"label":"Surface treatment","value":"Shot-blasted to SA 2.5"},{"label":"Primer","value":"80–120 microns"}]'::jsonb, '[{"src":"/images/gallery-crane-lift.jpg","alt":"Industrial Valve Plant — crane lifting a load on an industrial site","plate":"erection","label":"PLATE 01"},{"src":"/images/gallery-erection.jpg","alt":"Industrial Valve Plant — rigger working at height during steel erection","plate":"erection","label":"PLATE 02"},{"src":"/images/gallery-weld-detail.jpg","alt":"Industrial Valve Plant — welding a steel joint, arc light on the metal","plate":"blueprint","label":"PLATE 03"},{"src":"/images/gallery-shop-floor.jpg","alt":"Industrial Valve Plant — operator working a machine on the fabrication floor","plate":"plant","label":"PLATE 04"}]'::jsonb, 14)
ON CONFLICT (slug) DO UPDATE SET
  idx           = EXCLUDED.idx,
  name          = EXCLUDED.name,
  building_type = EXCLUDED.building_type,
  location      = EXCLUDED.location,
  year          = EXCLUDED.year,
  area          = EXCLUDED.area,
  scope         = EXCLUDED.scope,
  verified      = EXCLUDED.verified,
  photo         = EXCLUDED.photo,
  plate         = EXCLUDED.plate,
  overview      = EXCLUDED.overview,
  challenge     = EXCLUDED.challenge,
  approach      = EXCLUDED.approach,
  execution     = EXCLUDED.execution,
  result        = EXCLUDED.result,
  technical     = EXCLUDED.technical,
  gallery       = EXCLUDED.gallery,
  sort_order    = EXCLUDED.sort_order,
  updated_at    = now();

COMMIT;
